### ISSUE TITLE
How do I put the filename ???

### ISSUE THREAD

**Issue by etienne-sf** [jdunck/python-unicodecsv#89]
Hello,

The README.MD contains a simple sample. 

But where/how do I choose the filename and folder ?

>>> import unicodecsv as csv
>>> from io import BytesIO
>>> f = BytesIO()
>>> w = csv.writer(f, encoding='utf-8')
>>> _ = w.writerow((u'é', u'ñ'))
>>> _ = f.seek(0)
>>> r = csv.reader(f, encoding='utf-8')
>>> next(r) == [u'é', u'ñ']
True

**Comment by ryanhiebert** [comment]
You choose the filename when you open the file using the `open()` builtin command. If you're looking for something with deep support for Unicode, but at a sacrifice of speed, you might also consider the [`backports.csv`](https://github.com/ryanhiebert/backports.csv/) package. This one is a bit faster, but has some limitations on what kind of encodings you can use because it uses the builtin parser for Python 2 under the hood.

**Comment by etienne-sf** [comment]
Thanks for your comment. 

My issue, here is that I didn’t find a way to link this sample to the open file command 

This is trivial for a python expert. 

But this sample is of no help for a beginner like me. 
And your response doesn’t help, as it doesn’ t explain how to link the file to the sample I quote in my question. 

BTW, I found a way in the meanwhile. 

Etienne
